import test from 'node:test';import assert from 'node:assert/strict';
import {deliverInventoryQuestion} from '../tools/slack-heybilli-sync/stock-collector.mjs';
const question={id:'00000000-0000-4000-8000-000000000001',owner:'00000000-0000-4000-8000-000000000002',question_channel:'C123',question_text:'이름을 대조했지만 실보유수량 기록이 없습니다. 총보유·정비수량이 각각 몇 개인가요?',created_at:'2026-09-14T00:00:00Z'};
const root={ts:'1789344000.001',text:question.question_text,bot_id:'B1',metadata:{event_type:'inventory_risk_alert',event_payload:{id:question.id}}};
function fixture({history=[],attemptedAt=null,claim=true,allow=true,postFails=false,incomplete=false,changed=false}={}){
 const writes=[],calls=[];let posted=false;
 const api=async b=>{calls.push(b);if(b.operation==='claim')return {question:claim?{...question,attempted_at:attemptedAt}:null};if(b.operation==='attempt')return {allowed:allow};if(b.operation==='receipt'){assert.equal(b.receipt.messages[0].text,question.question_text);return {ok:true,posted:true};}throw Error('unexpected');};
 const slack=async(method,args)=>{if(method==='conversations.history')return {ok:true,messages:history,has_more:incomplete};if(method==='conversations.replies')return {ok:true,messages:[{...root,text:changed?'edited':root.text}]};throw Error('unexpected');};
 const post=async payload=>{writes.push(payload);posted=true;if(postFails)throw Error('accepted but response lost');return {ok:true,ts:root.ts};};
 return {run:()=>deliverInventoryQuestion(api,slack,post,{now:()=>Date.parse('2026-09-14T00:05:00Z')}),writes,calls};
}
test('question delivery requires a lease, attempt permission and exact reread receipt',async()=>{const f=fixture();assert.equal((await f.run()).posted,true);assert.equal(f.writes.length,1);assert.deepEqual(f.calls.map(c=>c.operation),['claim','attempt','receipt']);assert.equal(f.writes[0].metadata.event_payload.id,question.id);});
test('accepted but timed out question is reconciled without another message',async()=>{const failed=fixture({postFails:true});await assert.rejects(failed.run());assert.equal(failed.writes.length,1);const retry=fixture({history:[root],attemptedAt:'2026-09-14T00:01:00Z'});assert.equal((await retry.run()).posted,true);assert.equal(retry.writes.length,0);assert.equal(retry.calls.some(c=>c.operation==='attempt'),false);});
test('no lease, recent uncertain send, denied attempt and incomplete history never post',async()=>{for(const options of [{claim:false},{attemptedAt:'2026-09-14T00:04:50Z'},{allow:false},{incomplete:true}]){const f=fixture(options);await f.run().catch(()=>{});assert.equal(f.writes.length,0);assert.equal(f.calls.some(c=>c.operation==='receipt'),false);}});
test('question receipts on later history pages are found before posting',async()=>{let pages=0,posts=0;const api=async b=>b.operation==='claim'?{question}:b.operation==='receipt'?{ok:true,posted:true}:assert.fail('must not post');const slack=async(method,args)=>method==='conversations.replies'?{ok:true,messages:[root]}:++pages===1?{ok:true,messages:[],has_more:true,response_metadata:{next_cursor:'page2'}}:{ok:true,messages:[root]};const r=await deliverInventoryQuestion(api,slack,async()=>{posts++;});assert.equal(r.posted,true);assert.equal(pages,2);assert.equal(posts,0);});
test('edited question text cannot be acknowledged as the original question',async()=>{const f=fixture({history:[root],changed:true});await assert.rejects(f.run(),/원문/);assert.equal(f.writes.length,0);assert.equal(f.calls.some(c=>c.operation==='receipt'),false);});
