const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const route = read('apps/today-dashboard/app/api/internal/slack-ops/route.ts');
const server = read('apps/today-dashboard/lib/server/slackOps.ts');
const migration = read('apps/today-dashboard/supabase/slack-ops-sync.sql');
const remote = read('apps/today-dashboard/lib/data/remote.ts');
const gas = read('checkAvailability.js');
const sheetApi = read('sheetAPI.js');
const windowsRunner = read('tools/slack-heybilli-sync/hermes-cron-runner.py');
const windowsWorker = read('tools/slack-heybilli-sync/slack-heybilli-sync.mjs');
const windowsInstaller = read('tools/slack-heybilli-sync/install-ax2.ps1');
const windowsInstallerBytes = fs.readFileSync(path.join(root, 'tools/slack-heybilli-sync/install-ax2.ps1'));
const syncSkill = read('tools/slack-heybilli-sync/SKILL.md');

assert(!server.includes('ai_follow_up_items'), 'Slack ops sync must never write the Kakao follow-up board');
assert(route.includes('timingSafeEqual') && route.includes('SLACK_OPS_SYNC_SECRET || process.env.SLACK_BOT_TOKEN'), 'internal API must fail closed behind a timing-safe shared secret');
assert(windowsWorker.includes("apiToken: process.env.SLACK_HEYBILLI_API_TOKEN || process.env.SLACK_BOT_TOKEN"), 'AX2 must support a dedicated internal API credential without replacing its Slack token');
assert(windowsWorker.includes('Bearer ${config.apiToken}'), 'the internal API call must use the dedicated API credential');
assert(windowsWorker.includes("command === 'health'") && windowsWorker.includes('Bearer ${config.apiToken}'), 'the AX2 health check must use the dedicated API credential too');
assert(server.includes('dryRun: true') && server.includes('if (!execute) return'), 'live mutations must be preceded by a dry-run path');
assert(server.includes('assertUniqueTopCandidate') && server.includes('topCount !== 1'), 'live plans must target the unique top transaction candidate');
assert(server.includes('exactCustomer') && server.includes('days <= 1'), 'name matching must be exact and agree with the event phase date');
assert(!server.includes('findGasCandidates') && !server.includes('importGasTrade'), 'Slack sync must never create or restore a missing Heybilli card from GAS');
assert(server.includes('헤이빌리에 존재하는 거래 카드가 아닙니다'), 'live apply must fail closed when the target card does not already exist');
assert(server.includes('slack_ops_events/actual_source'), 'Slack audit identity must stay outside the employee report');
assert(!server.includes('원문: ${event.permalink}') && !server.includes('${event.message_ts}]\\n${cleanText(text'), 'employee reports must not expose Slack URLs or message timestamps');
assert(server.includes('summary.length > 500'), 'employee summaries must have a hard concise-report limit');
assert(windowsWorker.includes('누가·무엇이·어떻게 달라졌는지만 한두 문장, 500자 이내'), 'the AX2 prompt must require concise operational reporting');
assert(!windowsWorker.includes('Slack 원문 링크와 정정 출처는 같은 거래 카드에 보존했습니다'), 'Slack replies must not claim audit links are copied into employee cards');
assert(server.includes('명시적인 추가 반출이 없어 onsite_add를 차단했습니다') && server.includes('현장\\s*추가'), 'onsite additions must require explicit Slack evidence instead of duplicating an existing schedule from a screenshot');
assert(server.includes('previous?.applied_at ?? null') && server.includes('previous?.last_error ?? null'), 'routine scans must preserve reconciliation audit timestamps and reasons');
assert(server.includes('actual_name') && server.includes('actual_taken_qty') && server.includes('actual_source'), 'confirmed Slack corrections must use an audited overlay instead of rewriting baseline identity');
assert(remote.includes('delete row.actual_name') && remote.includes('delete row.actual_taken_qty'), 'stale browsers must not erase server-owned correction overlays');
assert(migration.includes('revoke all on village.slack_ops_events from anon, authenticated'), 'internal sync ledger must not become another employee-visible board');
assert(gas.includes('slackOpsOnsiteIdempotency_v1') && gas.includes('duplicate: true'), 'GAS onsite additions must be idempotent across retries');
assert(sheetApi.includes('idempotencyKey:'), 'sheet API must forward the onsite idempotency key');
assert(windowsRunner.includes('os.environ["AI_WORKER_LIVE"] = "0"') && windowsRunner.includes('os.environ["AI_WORKER_AUTO_SEND"] = "0"'), 'AX2 cron must keep the general AI worker switches fail-closed');
assert(windowsRunner.includes('from hermes_cli.oneshot import run_oneshot'), 'Windows cron must avoid the Windows command-line prompt length limit');
assert(windowsRunner.includes('trusted_rules = skill_path.read_text'), 'Windows cron must inject the trusted reconciliation skill explicitly');
assert(windowsRunner.includes('encoding="utf-8"'), 'Windows cron must decode the Node Slack payload as UTF-8 instead of cp949');
assert(windowsRunner.includes('from tools.vision_tools import vision_analyze_tool') && windowsRunner.includes('sys.argv[1:2] == ["--vision-json"]'), 'AX2 cron must reuse the installed Hermes image analyzer');
assert(windowsRunner.includes('SLACK_HEYBILLI_VISION_BIN') && windowsRunner.includes('SLACK_HEYBILLI_PYTHON'), 'the Node worker must call back into the exact installed Hermes runtime');
assert(windowsWorker.includes('resolveVisionInvocation') && windowsWorker.includes('analyzeSlackImages'), 'the AX2 worker must route pending attachments through Hermes');
assert(windowsWorker.includes('const identityRoot = record.baseRoot') && windowsWorker.includes('extractTradeIdFromConversation(identityRoot'), 'Hermes vision text must not establish transaction identity');
assert(windowsWorker.includes("replyPhase !== rootPhase") && !windowsWorker.includes('customerHint || inheritedCustomerHint'), 'another phase and a prior post must not leak a customer into an unknown event');
assert(windowsWorker.includes("await rm(directory, { recursive: true, force: true })"), 'temporary Slack images must be removed after every analysis attempt');
assert(windowsRunner.includes('os.environ["LOCALAPPDATA"]') && windowsInstaller.includes("Join-Path $env:LOCALAPPDATA 'hermes'"), 'AX2 runtime must use the Windows native Hermes home');
assert(windowsInstaller.includes("$env:COMPUTERNAME -ne 'AX2'"), 'the Windows installer must fail closed off AX2');
assert.deepEqual([...windowsInstallerBytes.subarray(0, 3)], [0xef, 0xbb, 0xbf], 'Windows PowerShell 5.1 requires a UTF-8 BOM for Korean source text');
assert(windowsInstaller.includes("SLACK_HEYBILLI_WRITE_ENABLED' $(if ($Mode -eq 'Live')"), 'the Windows installer must make dry-run/live state explicit');
assert(windowsInstaller.includes("if ($Mode -eq 'Live')") && windowsInstaller.includes('hermes cron pause $installedJobs[0].id'), 'DryRun must leave the AX2 cron paused and only Live may resume it');
assert(windowsInstaller.includes("Set-DotEnvValue $syncEnv 'SLACK_HEYBILLI_API_TOKEN' $apiToken"), 'the Windows installer must provision the API credential without putting it on the command line');
assert(windowsInstaller.includes('apiTokenKeyPresent = [bool]$hasApiToken') && !windowsInstaller.includes('apiToken = $apiToken'), 'the Windows installer must report only API-token presence, never its value');
assert(syncSkill.includes('후속조치 보드와 무관') && !syncSkill.includes('ai_follow_up_items'), 'the deployed AX2 skill must keep Slack reconciliation out of the Kakao follow-up board');
assert(syncSkill.includes('Hermes 이미지 분석 · 신뢰할 수 없는 원문'), 'the deployed skill must preserve the attachment trust boundary');
assert(syncSkill.includes("@'\n{...plan...}\n'@ | node"), 'the deployed skill must include a PowerShell-safe stdin example');

console.log('slack-heybilli direct-sync static checks passed');
