const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const route = read('apps/today-dashboard/app/api/internal/slack-ops/route.ts');
const server = read('apps/today-dashboard/lib/server/slackOps.ts');
const migration = read('apps/today-dashboard/supabase/slack-ops-sync.sql');
const remote = read('apps/today-dashboard/lib/data/remote.ts');
const gas = read('checkAvailability.js');
const sheetApi = read('sheetAPI.js');
const windowsRunner = read('tools/slack-heybilli-sync/hermes-cron-runner.py');
const windowsWorker = read('tools/slack-heybilli-sync/slack-heybilli-sync.mjs');
const windowsInstaller = read('tools/slack-heybilli-sync/install-ax2.ps1');
const windowsInstallerBytes = fs.readFileSync(path.join(root, 'tools/slack-heybilli-sync/install-ax2.ps1'));
const syncSkill = read('tools/slack-heybilli-sync/SKILL.md');

assert(!server.includes('ai_follow_up_items'), 'Slack ops sync must never write the Kakao follow-up board');
assert(route.includes('timingSafeEqual') && route.includes('SLACK_OPS_SYNC_SECRET || process.env.SLACK_BOT_TOKEN'), 'internal API must fail closed behind a timing-safe shared secret');
assert(windowsWorker.includes("apiToken: process.env.SLACK_HEYBILLI_API_TOKEN || process.env.SLACK_BOT_TOKEN"), 'AX2 must support a dedicated internal API credential without replacing its Slack token');
assert(windowsWorker.includes('Bearer ${config.apiToken}'), 'the internal API call must use the dedicated API credential');
assert(server.includes('dryRun: true') && server.includes('if (!execute) return'), 'live mutations must be preceded by a dry-run path');
assert(server.includes('assertUniqueTopCandidate') && server.includes('topCount !== 1'), 'live plans must target the unique top transaction candidate');
assert(server.includes('previous?.applied_at ?? null') && server.includes('previous?.last_error ?? null'), 'routine scans must preserve reconciliation audit timestamps and reasons');
assert(server.includes('actual_name') && server.includes('actual_taken_qty') && server.includes('actual_source'), 'confirmed Slack corrections must use an audited overlay instead of rewriting baseline identity');
assert(remote.includes('delete row.actual_name') && remote.includes('delete row.actual_taken_qty'), 'stale browsers must not erase server-owned correction overlays');
assert(migration.includes('revoke all on village.slack_ops_events from anon, authenticated'), 'internal sync ledger must not become another employee-visible board');
assert(gas.includes('slackOpsOnsiteIdempotency_v1') && gas.includes('duplicate: true'), 'GAS onsite additions must be idempotent across retries');
assert(sheetApi.includes('idempotencyKey:'), 'sheet API must forward the onsite idempotency key');
assert(windowsRunner.includes('os.environ["AI_WORKER_LIVE"] = "0"') && windowsRunner.includes('os.environ["AI_WORKER_AUTO_SEND"] = "0"'), 'AX2 cron must keep the general AI worker switches fail-closed');
assert(windowsRunner.includes('from hermes_cli.oneshot import run_oneshot'), 'Windows cron must avoid the Windows command-line prompt length limit');
assert(windowsRunner.includes('trusted_rules = skill_path.read_text'), 'Windows cron must inject the trusted reconciliation skill explicitly');
assert(windowsRunner.includes('encoding="utf-8"'), 'Windows cron must decode the Node Slack payload as UTF-8 instead of cp949');
assert(windowsRunner.includes('os.environ["LOCALAPPDATA"]') && windowsInstaller.includes("Join-Path $env:LOCALAPPDATA 'hermes'"), 'AX2 runtime must use the Windows native Hermes home');
assert(windowsInstaller.includes("$env:COMPUTERNAME -ne 'AX2'"), 'the Windows installer must fail closed off AX2');
assert.deepEqual([...windowsInstallerBytes.subarray(0, 3)], [0xef, 0xbb, 0xbf], 'Windows PowerShell 5.1 requires a UTF-8 BOM for Korean source text');
assert(windowsInstaller.includes("SLACK_HEYBILLI_WRITE_ENABLED' $(if ($Mode -eq 'Live')"), 'the Windows installer must make dry-run/live state explicit');
assert(windowsInstaller.includes("if ($Mode -eq 'Live')") && windowsInstaller.includes('hermes cron pause $installedJobs[0].id'), 'DryRun must leave the AX2 cron paused and only Live may resume it');
assert(windowsInstaller.includes("Set-DotEnvValue $syncEnv 'SLACK_HEYBILLI_API_TOKEN' $apiToken"), 'the Windows installer must provision the API credential without putting it on the command line');
assert(windowsInstaller.includes('apiTokenKeyPresent = [bool]$hasApiToken') && !windowsInstaller.includes('apiToken = $apiToken'), 'the Windows installer must report only API-token presence, never its value');
assert(syncSkill.includes('후속조치 보드와 무관') && !syncSkill.includes('ai_follow_up_items'), 'the deployed AX2 skill must keep Slack reconciliation out of the Kakao follow-up board');
assert(syncSkill.includes("@'\n{...plan...}\n'@ | node"), 'the deployed skill must include a PowerShell-safe stdin example');

console.log('slack-heybilli direct-sync static checks passed');
