-- Kakao DOM Bridge queue table
-- Run this in Supabase SQL Editor.
-- The local bridge inserts with the service-role key; do NOT expose that key to the Chrome extension.

create table if not exists public.ai_processing_events (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'kakao_channel_manager_dom',
  status text not null default 'pending_ai_review',
  room_key text,
  event_hash text,
  preview_text text,
  unread_count integer,
  detected_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  error_message text
);

create index if not exists ai_processing_events_status_created_idx
  on public.ai_processing_events (status, created_at desc);

create index if not exists ai_processing_events_source_created_idx
  on public.ai_processing_events (source, created_at desc);

create index if not exists ai_processing_events_room_created_idx
  on public.ai_processing_events (room_key, created_at desc);

create unique index if not exists ai_processing_events_event_hash_unique_idx
  on public.ai_processing_events (event_hash)
  where event_hash is not null;

-- Human follow-up/action board generated by the AI worker.
-- The worker inserts only AI-decided follow-up items; this table is the source
-- for the remote dashboard and should not expose service-role credentials to browsers.
create table if not exists public.ai_follow_up_items (
  id uuid primary key default gen_random_uuid(),
  follow_up_key text not null unique,
  source text not null default 'kakao_ai_worker',
  job_id uuid references public.ai_processing_events(id) on delete set null,
  room_key text,
  customer_name text,
  type text not null default 'reply_needed',
  priority text not null default 'normal',
  status text not null default 'open',
  title text not null,
  summary text,
  recommended_action text,
  suggested_reply_draft text,
  evidence jsonb not null default '[]'::jsonb,
  blocking_reason text,
  due_hint text,
  decision_classification text,
  decision_confidence text,
  slack_channel_name text,
  slack_channel_id text,
  slack_message_ts text,
  slack_thread_ts text,
  slack_delivery_status text not null default 'pending',
  slack_delivery_error text,
  slack_delivered_at timestamptz,
  slack_action_type text,
  slack_action_status text not null default 'idle',
  slack_action_requested_at timestamptz,
  slack_action_handled_at timestamptz,
  slack_action_error text,
  slack_draft_override text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.ai_follow_up_items
  add column if not exists slack_channel_name text,
  add column if not exists slack_channel_id text,
  add column if not exists slack_message_ts text,
  add column if not exists slack_thread_ts text,
  add column if not exists slack_delivery_status text not null default 'pending',
  add column if not exists slack_delivery_error text,
  add column if not exists slack_delivered_at timestamptz,
  add column if not exists slack_action_type text,
  add column if not exists slack_action_status text not null default 'idle',
  add column if not exists slack_action_requested_at timestamptz,
  add column if not exists slack_action_handled_at timestamptz,
  add column if not exists slack_action_error text,
  add column if not exists slack_draft_override text;

create index if not exists ai_follow_up_items_status_priority_idx
  on public.ai_follow_up_items (status, priority, created_at desc);

create index if not exists ai_follow_up_items_type_status_idx
  on public.ai_follow_up_items (type, status, created_at desc);

create index if not exists ai_follow_up_items_customer_idx
  on public.ai_follow_up_items (customer_name, created_at desc);

create index if not exists ai_follow_up_items_slack_delivery_idx
  on public.ai_follow_up_items (slack_delivery_status, created_at desc);

create index if not exists ai_follow_up_items_slack_action_idx
  on public.ai_follow_up_items (slack_action_status, slack_action_requested_at asc);

create or replace function public.set_ai_processing_events_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_ai_processing_events_updated_at on public.ai_processing_events;
create trigger trg_ai_processing_events_updated_at
before update on public.ai_processing_events
for each row
execute function public.set_ai_processing_events_updated_at();

create or replace function public.set_ai_follow_up_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if new.status in ('done', 'dismissed') and old.status is distinct from new.status and new.completed_at is null then
    new.completed_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_ai_follow_up_items_updated_at on public.ai_follow_up_items;
create trigger trg_ai_follow_up_items_updated_at
before update on public.ai_follow_up_items
for each row
execute function public.set_ai_follow_up_items_updated_at();

-- Recommended: keep RLS enabled for browser/client access, but service-role inserts bypass RLS.
alter table public.ai_processing_events enable row level security;
alter table public.ai_follow_up_items enable row level security;

-- No public policies are created here on purpose.
-- If a dashboard/client needs read access later, add a narrow authenticated read policy then.
