import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { collectRuntime, RUNTIME_SCHEMA_VERSION, serializeRuntimeDiagnostics } from './runtime-probe.mjs';
function fake(overrides={}){return async(file)=>{if(file==='which')return {stdout:overrides.path??'/opt/codex'};if(file==='/opt/codex')return {stdout:overrides.version??'codex 0.147.0\n'};if(file==='git'){if(overrides.branchFailure)throw Object.assign(new Error('raw'),{code:'ENOENT'});return {stdout:'codex/test\n'};}return {stdout:''};};}
test('runtime diagnostics use a separate strict non-contract schema',async()=>{const dir=await mkdtemp(join(tmpdir(),'gate0-runtime-'));try{const r=await collectRuntime({exec:fake(),cwd:dir,configuredMcp:[{name:'node_repl',status:'available'}],now:()=> '2026-08-24T00:00:00.000Z'});assert.equal(r.schemaVersion,RUNTIME_SCHEMA_VERSION);assert.equal(r.status,'AVAILABLE');assert.equal(r.probeId,undefined);assert.deepEqual(r.node,{path:process.execPath,version:process.versions.node});assert.deepEqual(r.codex,{path:'/opt/codex',version:'0.147.0'});assert.deepEqual(JSON.parse(serializeRuntimeDiagnostics(r)),r);}finally{await rm(dir,{recursive:true,force:true});}});
test('empty path, version failure, and branch failure are blocked diagnostics',async()=>{const empty=await collectRuntime({exec:fake({path:''})});assert.equal(empty.errorClass,'empty_path');const failed=await collectRuntime({exec:async(file)=>{if(file==='which')return {stdout:'/opt/codex'};throw Object.assign(new Error('raw secret'),{code:'ENOENT'});}});assert.equal(failed.errorClass,'version_failed');const branch=await collectRuntime({exec:fake({branchFailure:true})});assert.equal(branch.status,'BLOCKED');assert.equal(branch.errorClass,'command_failed');assert.throws(()=>serializeRuntimeDiagnostics({...branch,probeId:'launchagent_security'}),/invalid runtime diagnostics keys/);});
